break_off_sigma: 3
viewing_dist: 1
dot_pitch: 0.00035
fov_beta: 1.5
fov_gamma: 5 

eps: 0.0000001

parvo_sigmas: 
  - 48
  - 24
  - 12
  - 6
  - 3

magno_sigmas: 
  - 64
  - 32
  - 16
  - 8
  - 4

interpolation_sigmas:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32

n_bins_weibull: 1000

color_weighting_e:
  - 0.3
  - 0.58
  - 0.11
color_weighting_el:
  - 0.25
  - 0.25
  - -0.5
color_weighting_ell:
  - 0.5
  - -0.5
  - 0.0